### PR TITLE
Split commands

### PR DESCRIPTION
**Pull request by hkupty**
This ensures that we can have any combination
of `wait`, `silent`, `tab` and the newly added
by this PR `vertical` or `split` without having
to implement all the commands as combinations of
`--remote--{verical,split}{--silent,}{--wait,}`.

### CODE REVIEW

**Comment by mhinz** [comment]
Vim doesn't have these options. The `--remote` family is there for backward compatibility.

Is there any use case that can't be solved with nvr currently?

**Comment by hkupty** [comment]
Yes, I need to combine `-O` with wait, so that I can reuse a neovim instance for git commit/rebase -i/hub pull-request and any other command that I need to wait.

If use remote-wait, I'll loose the terminal after I close the buffer.

**Comment by hkupty** [comment]
Hum.. That makes sense.. But what about having `--wait` (or a short option such as `-w`)?

I'm totally fine with the suggestion you made, though. :)

**Comment by mhinz** [comment]
Cool! Then let's just roll with that and don't add new code until there's a real need for `--wait`.

(`-w` can't be used because some people use _nvr_ as a drop-in replacement for _vim_ and it has a `-w` option already.)

Thanks for bringing this up, though! ✨

**Pull request closed without merging**
