### PR TITLE
Fix readme name in setup.py

### PR DESCRIPTION
**Pull request by teto**
else python setup.py develop --user stops working

### CODE REVIEW

**Comment by poppyschmo** [comment]
I think you have to run the `*.md` through pandoc to get the `*.rst` (like in the `Makefile`), no? Not sure if it's required for sdist/wheel, but [this] (https://packaging.python.org/distributing/#readme-rst) makes it sound like it's not.

**Comment by mhinz** [comment]
Yup, the Makefile has a "rst" target. It's required by PyPI as far as I know.

But apparently Github knows how to handle rst, so README.md could be removed.

**Comment by teto** [comment]
Why do they write "should" when it seems needed ?! I checked my own package using markdown and indeed the markdown is not interpreted. 
Thanks for the information both of you and sorry for the noise ! On my way to update my packages (does not sound that fun
http://inre.dundeemt.com/2014-05-04/pypi-vs-readme-rst-a-tale-of-frustration-and-unnecessary-binding/ )

**Comment by mhinz** [comment]
Well, I'm no terribly huge fan of PyPI anyway.. had me fair share of bugs in my relatively short Python time. Anyway, I think it's successor, warehouse, is supposed to support Markdown: https://pypi.org/project/neovim-remote

**Pull request closed without merging**
